# Generated by Django 5.2.4 on 2025-08-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Plumbing', 'Plumbing'), ('Electrical Work', 'Electrical Work'), ('Carpentry', 'Carpentry'), ('Painting', 'Painting'), ('Cleaning', 'Cleaning'), ('Gardening', 'Gardening'), ('AC Repair', 'AC Repair'), ('Appliance Repair', 'Appliance Repair'), ('Tutoring', 'Tutoring'), ('Web Development', 'Web Development'), ('Graphic Design', 'Graphic Design'), ('Photography', 'Photography'), ('Catering', 'Catering'), ('Beauty Services', 'Beauty Services'), ('Massage Therapy', 'Massage Therapy'), ('Pet Care', 'Pet Care'), ('House Sitting', 'House Sitting'), ('Moving Services', 'Moving Services'), ('Car Wash', 'Car Wash'), ('Laundry Services', 'Laundry Services')], max_length=59)),
            ],
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='working_hours',
            field=models.CharField(choices=[('24/7 Availability', '24/7 Availability'), ('Morning (6 AM - 12 PM)', 'Morning (6 AM - 12 PM)'), ('Afternoon (12 PM - 6 PM)', 'Afternoon (12 PM - 6 PM)'), ('Evening (6 PM - 10 PM)', 'Evening (6 PM - 10 PM)'), ('Night (10 PM - 6 AM)', 'Night (10 PM - 6 AM)'), ('Flexible Hours', 'Flexible Hours')], default='Flexible', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Weekends Only', 'Weekends Only'), ('Flexible', 'Flexible')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='service_area',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Lalitpur', 'Lalitpur'), ('Bhaktapur', 'Bhaktapur'), ('Birtamode', 'Birtamode'), ('Bhadrapur', 'Bhadrapur'), ('Biratnagar', 'Biratnagar'), ('Pokhara', 'Pokhara'), ('Nepalgunj', 'Nepalgunj'), ('Butwal', 'Butwal'), ('Hetauda', 'Hetauda')], max_length=50),
        ),
        migrations.AddField(
            model_name='providerprofile',
            name='available_skills',
            field=models.ManyToManyField(to='users.skill'),
        ),
    ]
