# Generated by Django 5.2.4 on 2025-08-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_skill_providerprofile_working_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerprofile',
            name='working_hours',
            field=models.CharField(choices=[('24/7 Availability', '24/7 Availability'), ('Morning (6 AM - 12 PM)', 'Morning (6 AM - 12 PM)'), ('Afternoon (12 PM - 6 PM)', 'Afternoon (12 PM - 6 PM)'), ('Evening (6 PM - 10 PM)', 'Evening (6 PM - 10 PM)'), ('Night (10 PM - 6 AM)', 'Night (10 PM - 6 AM)'), ('Flexible Hours', 'Flexible Hours')], default='Flexible', max_length=50),
        ),
    ]
