# Generated by Django 5.2.4 on 2025-08-23 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='providerservice',
            name='provider',
            field=models.ForeignKey(limit_choices_to={'role': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_services', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerservice',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.baseservice'),
        ),
        migrations.AlterUniqueTogether(
            name='providerservice',
            unique_together={('provider', 'services')},
        ),
    ]
