# Generated by Django 5.2.4 on 2025-08-23 08:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='time',
            field=models.TimeField(default=datetime.time(8, 16, 20, 569144)),
            preserve_default=False,
        ),
    ]
