# Generated by Django 5.2.4 on 2025-08-23 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointments_time'),
        ('users', '0003_alter_providerprofile_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_received', to='users.providerprofile'),
        ),
    ]
