# Generated by Django 5.2.4 on 2025-08-25 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointments_appointment_date'),
        ('users', '0003_alter_providerprofile_working_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_made', to='users.customerprofile'),
        ),
    ]
